scalar Upload

type StorageSectionResult {
    id: ID!
    name: String!
    attributes: [String!]!
}

type DataPair {
    key: String!
    value: String
}

type StorageItemResult {
    id: ID!
    name: String!
    metadata: DataPair
}

type UploadResult {
    success: Boolean!
    attachmentId: ID
    errorMessage: String
}

type Query {
    status: String
    retrieveStorageSections: [StorageSectionResult!]!
    retrieveStorageItems(sectionId: ID!): [StorageItemResult!]!
}

type Mutation {
    createStorageSection(name: String!, attributes: [String!]!): StorageSectionResult!
    uploadDocument(itemId: ID!, file: Upload!): UploadResult!
}